### ISSUE TITLE
[BUG] Dialogue options still continue processing even when user walks away during chat.

### ISSUE THREAD

**Issue by src52** [rune-js/server#305]
**Describe the bug**
If you speak to another NPC and walk away mid-conversation, instead of closing all dialogue interfaces, the next available option dialogue displays, even if the user didn't traverse down that part of the dialogue tree.

**To Reproduce**
1. Speak with an NPC with an option dialogue.
2. Before the option dialogue appears, cancel the dialogue interaction by walking away.
3. Each click that you make while walking away will display the next set of option choices from the dialogue, even if the player didn't go down that particular branch of the dialogue tree.

**Expected behavior**
All dialogues should close when walking away from a dialogue interaction with an NPC.

**Screenshots**
https://i.imgur.com/vPSgVop.mp4

**Comment by hallowatcher** [comment]
is this on my romeo and juliet branch?

**Comment by src52** [comment]
> is this on my romeo and juliet branch?

Yes, maybe I should've created a bug report on your specific fork instead, but I wasn't sure if it was caused by yours in particular.

**Comment by Tynarus** [comment]
This should be fixed with the new action handling system, but feel free to re-open if it persists when the PR is ready to merge.

**Comment by hallowatcher** [comment]
I know why this happens, and IMO it's an issue still, depending on the perspective you look at it.

Say you have this code:
```javascript
async function talkToNpc() {
  await dialog([ ... ]);
  
  openBankInterface();
}
```

If you talk to the NPC, and walk away mid dialogue, the `openBankInterface()` function will always be reached, no matter what. Right now, this is hackily solved by checking if the dialogue was "success".

```javascript
async function talkToNpc() {
  const success = await dialog([ ... ]);
  
  if (success) {
    openBankInterface();
  }
}
```

But what if you have multiple dialogues in there (the case for some quests where there is a `world.tick` between each dialogue). This solution is hella ugly
```javascript
async function talkToNpc() {
  const successOne = await dialog([ ... ]);
  
  if (successOne) {
    const successTwo = await dialog([ ... ]);

    if (successTwo) {
      // Do something important
    }
  }
}
```

This can easily be fixed by throwing in `dialogue.ts`, line 589 (I think). I'll look into it, unless we still want to depend on the return value of the dialogue function (current solution)
